GPU_BUDGET_MB = 6 * 1024

FAST_SINGLE_INSTANCE_VRAM_MB = 91
THINKING_SINGLE_INSTANCE_VRAM_MB = 123

FAST_DEFAULT_INSTANCE_PARALLELISM = max(1, GPU_BUDGET_MB // FAST_SINGLE_INSTANCE_VRAM_MB)
THINKING_DEFAULT_INSTANCE_PARALLELISM = max(1, GPU_BUDGET_MB // THINKING_SINGLE_INSTANCE_VRAM_MB)


def default_instance_parallelism(mode: str) -> int:
    normalized = str(mode).strip().lower()
    if normalized == "fast":
        return FAST_DEFAULT_INSTANCE_PARALLELISM
    return THINKING_DEFAULT_INSTANCE_PARALLELISM
